### ISSUE TITLE
Reinitialize tree values

### ISSUE THREAD

**Issue by christophervistal25** [Remi-Leclercq-Blondel/treeMaker#7]
How can I re-initialize the tree values
I'm using vanilla javascript.

can I use the library for vue js?

**Comment by roumilb** [comment]
I've just made a new version and you can now update the tree by calling the function `treeMaker` again.
It will destroy the current tree and recreate it again.

Yes you can use it in vue js, you can install it in your projet with the command `npm install --save @roumi/treemaker` and then import like that `import treeMaker from '@roumi/treemaker'`
There is an example in the readme :)

**Comment by christophervistal25** [comment]
Nice! Update
is there any method for setting values for tree

**Comment by roumilb** [comment]
The only solution for now is to call the `treeMaker` function with all the parameters
